apiVersion: v1
kind: Service
metadata:
  name: aihost-frontend-service
  namespace: aihost_mvp
spec:
  selector:
    app: aihost-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
